let suggestions = [
    "News API",
    "Github",
    "Cricket News",
    "YasirObaibullah",
    "YouTuber News",
    "Top News",
    "ukraine russia news",
    "Bollywood News",
    "Good places in bangalore",
    "W3 School",
    "Facebook",
    "twitter",
    "BBC News",
    "NDTV India",
    "News Tak",
    "Gmail",
    "Top Web Developer",
    "YouTube",
    "Crypto News",
    "Stock market News",
    "bangalore news today live",
    "Top News in US",
    "linkedin",
    "cricbuzz",
    "google",
    "top tech news",
];